[build]
  publish = "dist"
  command = "git config --global url.\"https://${GH_TOKEN}@github.com/\".insteadOf \"ssh://git@github.com/\" && npm install && npm run build"

[[redirects]]
  from = "/openapi.json"
  to = "/openapi.json"
  status = 200

[[redirects]]
  from = "/*/openapi.json"
  to = "/:splat/openapi.json"
  status = 200

# spa fallback for any route without a pre-rendered html file
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
